# Generated by Django 3.2.6 on 2021-09-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.addon'),
        ),
    ]
