# Generated by Django 3.2.6 on 2021-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210912_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
        ),
    ]
