# Generated by Django 3.2.6 on 2021-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
