# Generated by Django 3.2.6 on 2021-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_bundle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='slug',
        ),
    ]
