# Generated by Django 3.2.6 on 2021-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_bundle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_slug',
            field=models.SlugField(default='bundle slug', max_length=200),
        ),
    ]
