# Generated by Django 3.2.6 on 2021-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_bundle_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='bundle_slug',
            field=models.SlugField(default='bundle slug', max_length=200, unique=True),
        ),
    ]
