# Generated by Django 3.2.6 on 2021-09-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_bundle_bundle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='bundle_slug',
        ),
    ]
