# Generated by Django 3.2.6 on 2021-08-31 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('blog_subheading_1', models.CharField(max_length=50)),
                ('blog_content_1', models.TextField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('blog_subheading_2', models.CharField(max_length=50)),
                ('blog_content_2', models.TextField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('blog_subheading_3', models.CharField(blank=True, max_length=55, null=True)),
                ('blog_content_3', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)])),
            ],
        ),
    ]
