# Generated by Django 3.2.6 on 2021-09-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='bundle',
        ),
    ]
