# Generated by Django 3.2.6 on 2021-08-31 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casestudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=1024)),
                ('github_url', models.URLField(max_length=1024)),
                ('study_subheading_1', models.CharField(max_length=50)),
                ('study_content_1', models.TextField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('study_subheading_2', models.CharField(max_length=50)),
                ('study_content_2', models.TextField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('study_subheading_3', models.CharField(blank=True, max_length=55, null=True)),
                ('study_content_3', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)])),
            ],
        ),
    ]
