# Generated by Django 3.2.6 on 2021-09-02 20:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='url',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='study_content_1',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='study_content_2',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='study_content_3',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='study_subheading_1',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='study_subheading_2',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='study_subheading_3',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='case_study_content',
            field=ckeditor.fields.RichTextField(default='Case study content goes here'),
        ),
    ]
