# Generated by Django 3.2.6 on 2021-09-03 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_auto_20210902_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='heading',
            field=models.CharField(default='Heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='case_study_content',
            field=ckeditor.fields.RichTextField(default='Case study content'),
        ),
    ]
