# Generated by Django 3.2.6 on 2021-09-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0003_auto_20210903_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'verbose_name_plural': 'Casestudies'},
        ),
    ]
